"""added image scraping

Revision ID: 100a34b33305
Revises: 27a876882845
Create Date: 2024-07-17 21:13:00.512044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100a34b33305'
down_revision = '27a876882845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pictureblob', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('pictureblob')

    # ### end Alembic commands ###
