"""added events table

Revision ID: 15e503480161
Revises: 100a34b33305
Create Date: 2024-07-21 20:48:38.304156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e503480161'
down_revision = '100a34b33305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('startsOn', sa.DateTime(), nullable=True),
    sa.Column('endsOn', sa.DateTime(), nullable=True),
    sa.Column('imagePath', sa.String(length=100), nullable=True),
    sa.Column('pictureblob', sa.LargeBinary(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('categorynames', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('club_category_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_category_relation',
    sa.Column('clubid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('categoryname', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('clubid', 'categoryname')
    )
    op.drop_table('events')
    # ### end Alembic commands ###
