"""Add social media links to Club model

Revision ID: 1cbf9952a614
Revises: 
Create Date: 2024-07-03 15:05:44.234866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbf9952a614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('website')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('youtube')
        batch_op.drop_column('instagram')

    # ### end Alembic commands ###
