"""fixed nulls in rating table

Revision ID: 22f9cf4077bf
Revises: aabde6d27378
Create Date: 2024-07-24 18:35:57.215441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f9cf4077bf'
down_revision = 'aabde6d27378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('club_value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('member_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('member_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('club_value',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
