"""value rating criteria added

Revision ID: 55c92496bcda
Revises: e8e2d2c68b66
Create Date: 2024-07-24 16:32:13.296835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c92496bcda'
down_revision = 'e8e2d2c68b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clubvalue', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('clubvalue')

    # ### end Alembic commands ###
