"""additional rating criterias

Revision ID: aabde6d27378
Revises: ba43671ce2db
Create Date: 2024-07-24 18:31:34.865443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabde6d27378'
down_revision = 'ba43671ce2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('member_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('member_count')
        batch_op.drop_column('club_value')

    # ### end Alembic commands ###
