"""restoring previous migration

Revision ID: ba43671ce2db
Revises: 55c92496bcda
Create Date: 2024-07-24 18:23:19.925036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba43671ce2db'
down_revision = '55c92496bcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('clubvalue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clubvalue', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
