"""rating table added

Revision ID: c5cf61521a50
Revises: c61c457c5ff3
Create Date: 2024-07-22 17:22:03.565378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cf61521a50'
down_revision = 'c61c457c5ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=100), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('meeting_frequency', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
