"""Fixed nulls

Revision ID: d9f6c64162ff
Revises: d0b4565f6f6a
Create Date: 2024-07-05 21:02:53.245091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f6c64162ff'
down_revision = 'd0b4565f6f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('profilepicture',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('profilepicture',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
