"""Initial migration

Revision ID: e5da5346ee29
Revises: 9aa3155a029a
Create Date: 2024-07-03 15:41:02.967926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5da5346ee29'
down_revision = '9aa3155a029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_club')
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('instagram',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('youtube',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('facebook',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('twitter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['club_name'], ['name'])
        batch_op.drop_column('club_id')

    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['club_name'], ['name'])
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])
        batch_op.drop_column('club_name')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])
        batch_op.drop_column('club_name')

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('twitter',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('facebook',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('youtube',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('instagram',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('_alembic_tmp_club',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('shortbio', sa.VARCHAR(length=200), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=False),
    sa.Column('instagram', sa.VARCHAR(length=100), nullable=True),
    sa.Column('youtube', sa.VARCHAR(length=100), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=100), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=100), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=100), nullable=True)
    )
    # ### end Alembic commands ###
