"""fixing comment in rating table

Revision ID: e8e2d2c68b66
Revises: 8973674dd567
Create Date: 2024-07-22 18:23:01.754043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e2d2c68b66'
down_revision = '8973674dd567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('overall_rating', sa.FLOAT(), nullable=False),
    sa.Column('meeting_frequency', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
