"""updated some var names in rating

Revision ID: f38aa841779e
Revises: 55c92496bcda
Create Date: 2024-07-24 16:56:25.271677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38aa841779e'
down_revision = '55c92496bcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clubid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('overallrating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('meetingfrequency', sa.Float(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['clubid'], ['id'])
        batch_op.drop_column('overall_rating')
        batch_op.drop_column('meeting_frequency')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('meeting_frequency', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('overall_rating', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])
        batch_op.drop_column('meetingfrequency')
        batch_op.drop_column('overallrating')
        batch_op.drop_column('clubid')

    # ### end Alembic commands ###
